### ISSUE TITLE
Issues with RViz model

### ISSUE THREAD

**Issue by servetcoskun** [mindThomas/JetsonCar-Simulation#1]
Hi Thomas,

Thank you for the work you have done here, it has really helped me.
I am using your xacro files as inspiration for a robot I am building which is also a 4WD robot. I was having issues with my wheels being stuck to base_link and could not figure out why, so I cloned the repository here as a sanity check. To my surprise the wheels were also stuck to base_link when launching rviz.launch in jetsoncar_description.

I was only able to see the model once with the wheels stuck to base_link, launching the file now shows all the components smashed together around base_link. It looks like /tf is not being published so I suspect it is specific to my system which is running ROS Melodic.

Any chance you can help me figure out what is going on here? I have attached a gif of what I am currently experiencing. FYI I did comment out the joint_state_publisher gui.

![jetsoncar-rviz-sim](https://user-images.githubusercontent.com/5569716/77349027-b034c300-6d3a-11ea-9bf2-42f7035a0aef.gif)

Thanks in advance

**Comment by ghost** [comment]
This repository has been deprecated. Please try again with the latest code from: https://github.com/mindThomas/JetsonCar-Gazebo
